### PR TITLE
Ls product

### LINKED ISSUE #2: Allow developers to access Product resource
Verbs to be supported

1. GET
1. POST
1. PUT
1. DELETE

User should be able to GET a list of products, and GET a single product.

### PR DESCRIPTION
**Pull request by Levi-Schubert**
Closes #2 

# Changes Made
1. created product model, serializer, viewset, and router config
1. has FK to customer and product_type
1. added docstrings to previous tables authored by myself

# Steps to test
1. fetch all & `git checkout lsProduct`
1. delete migrations folder and db.sqlite
1. run `python3 manage.py makemigrations api` & `python3 manage.py migrate`
1. start the server
1. add customers and product types for testing
1. attempt to get, post, put, and delete product
1. attempt to delete a product type, it should remove and products that have the product type

## Reviewers
@Deanna2000 
@MatthewKelly12

### CODE REVIEW

**Comment by Deanna2000** [comment]
Looks good Bud

**Comment by Megraohoh** [comment]
resulted outcome not wanted

```
{
    "detail": "Not found."
}
```

**Comment by Deanna2000** [comment]
Ok, products are deleted when a product-type is removed

**Comment by MatthewKelly12** [comment]
👍 
Working great!! 
Ready to merge

**Pull request merged**
